// App.jsx — GENERATED by assemble_project(). Do not edit by hand;
// re-run assemble_project() to regenerate. Section components must not
// touch this file (it is a shared/assembly-owned file).
// page_title: Introducing Muse: The World’s First Personal AI Agent Built for Everyone
// source_url: https://about.fb.com/news/2026/09/introducing-muse-personal-ai-agent/
// sections: 8

import HeaderSection from "./components/sections/header/HeaderSection.jsx";
import Header2Section from "./components/sections/header-2/Header2Section.jsx";
import Section2Section from "./components/sections/section-2/Section2Section.jsx";
import Section3Section from "./components/sections/section-3/Section3Section.jsx";
import Section4Section from "./components/sections/section-4/Section4Section.jsx";
import Section5Section from "./components/sections/section-5/Section5Section.jsx";
import Section6Section from "./components/sections/section-6/Section6Section.jsx";
import FooterSection from "./components/sections/footer/FooterSection.jsx";

function StudyBanner() {
  const playHero = () => {
    window.dispatchEvent(new Event("pwc-play-hero"));
  };
  return (
    <div className="pwc-study-banner" role="note">
      <strong>方法 B · Perfect-Web-Clone · pwc assemble · :43212</strong>
      {" · "}
      <button
        type="button"
        data-hero-play="true"
        className="pwc-banner-play"
        onClick={playHero}
      >
        ▶ Play hero video
      </button>
      {" · "}
      study clone · not an official Meta page ·{" "}
      <a
        href="https://about.fb.com/news/2026/09/introducing-muse-personal-ai-agent/"
        target="_blank"
        rel="noreferrer"
      >
        原站 / original
      </a>
      {" · "}
      <a href="/NOTES.md" target="_blank" rel="noreferrer">
        方法笔记 / notes
      </a>
    </div>
  );
}

export default function App() {
  return (
    <>
      <StudyBanner />
      <div data-pwc-section="header">
        <HeaderSection />
      </div>
      <div data-pwc-section="header-2">
        <Header2Section />
      </div>
      <div data-pwc-section="section-2">
        <Section2Section />
      </div>
      <div data-pwc-section="section-3">
        <Section3Section />
      </div>
      <div data-pwc-section="section-4">
        <Section4Section />
      </div>
      <div data-pwc-section="section-5">
        <Section5Section />
      </div>
      <div data-pwc-section="section-6">
        <Section6Section />
      </div>
      <div data-pwc-section="footer">
        <FooterSection />
      </div>
    </>
  );
}
